<robot name="gazebo_control" xmlns:xacro="http://wiki.ros.org/xacro">

    <!-- 控制器 -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>false</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishOdomTF>true</publishOdomTF>
            <publishWheelJointState>true</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <legacyMode>true</legacyMode>
            <leftJoint>left2link</leftJoint>                            <!-- 左轮 -->
            <rightJoint>right2link</rightJoint>                         <!-- 右轮 -->
            <wheelSeparation>${wheel_joint_y * 2}</wheelSeparation>     <!-- 车轮间距 -->
            <wheelDiameter>${wheel_radius * 2}</wheelDiameter>          <!-- 车轮直径 -->
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic>                        <!-- 运动控制话题 -->
            <odometryFrame>odom</odometryFrame> 
            <odometryTopic>odom</odometryTopic>                         <!-- 里程计话题 -->
            <robotBaseFrame>base_footprint</robotBaseFrame>             <!-- 根坐标系 -->
        </plugin>
    </gazebo>

</robot>


