<!-- 激光雷达 -->
<robot name="robot_laser" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="laser_radius" value="0.04" />
    <xacro:property name="laser_height" value="0.03" />
    <xacro:property name="laser_mass" value="0.15" />
    <xacro:property name="laser_joint_x" value="0.18" />
    <xacro:property name="laser_joint_y" value="0.0" />
    <xacro:property name="laser_joint_z" value="${base_height/2 + laser_height/2}" />

    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_height}"/>
            </geometry>
            <material name="Black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_height}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${laser_mass}" r="${laser_radius}" h="${laser_height}"/>
    </link>
    <gazebo reference="laser">
        <material>Gazebo/Black</material>
    </gazebo>
    <!-- 雷达和base_link之间的joint -->
    <joint name="laser2link" type="fixed">
        <parent link="base_link"/>
        <child link="laser"/>
        <origin xyz="${laser_joint_x} ${laser_joint_y} ${laser_joint_z}" rpy="0.0 0.0 0.0"/>
    </joint>

</robot>